// Generated by scripts/build-client.js; edit src/client-entry.js, src/process-plan.js and src/fold-runtime.js.
window.__ModuleLoader__.load({
  id: 'dsh-thought-fold',
  factory: (require) => {
    const React = require('react');
    const { useCallback, useEffect, useState } = React;
    const h = React.createElement;

    const DEFAULT_CONFIG = Object.freeze({
      enabled: true,
      showLiveHud: true,
      foldStyle: 'codex'
    });

    const ICONS = {
      brain: 'M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96.44 2.5 2.5 0 0 1-2.96-3.08 3 3 0 0 1-.34-5.58 2.5 2.5 0 0 1 1.32-4.24A2.5 2.5 0 0 1 9.5 2zm5 0A2.5 2.5 0 0 1 17 4.5a2.5 2.5 0 0 1 1.32 4.24 3 3 0 0 1-.34 5.58 2.5 2.5 0 0 1-2.96 3.08A2.5 2.5 0 0 1 12 19.5v-15A2.5 2.5 0 0 1 14.5 2z',
      check: 'M20 6 9 17l-5-5',
      info: 'M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2zm1 15h-2v-6h2zm0-8h-2V7h2z',
      sliders: 'M4 21v-7m0-4V3m8 18v-9m0-4V3m8 18v-5m0-4V3M1 14h6m2-6h6m2 8h6',
      palette: 'M12 2a10 10 0 0 0 0 20h1.2a2.3 2.3 0 0 0 0-4.6h-1.4a1.8 1.8 0 0 1 0-3.6H14a8 8 0 0 0 0-16h-2zM7.5 9.5h.01M9.5 6.5h.01M14 6h.01M17 9h.01',
      shield: 'M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10zm-3-10 2 2 4-4'
    };

    function Icon({ name, size = 16 }) {
      return h('svg', {
        width: size,
        height: size,
        viewBox: '0 0 24 24',
        fill: 'none',
        stroke: 'currentColor',
        strokeWidth: 2,
        strokeLinecap: 'round',
        strokeLinejoin: 'round',
        'aria-hidden': true
      }, h('path', { d: ICONS[name] || ICONS.brain }));
    }

    const STYLE_ID = 'dsh-thought-fold-safe-styles';
    const ROOT_ATTRIBUTE = 'data-dsh-thought-fold';
    const CSS = `
      :root[data-dsh-thought-fold] [data-chat-flow-kind="turn-process"] {
        display: flex !important;
        justify-content: flex-start !important;
        align-items: center !important;
        width: 100% !important;
        margin-block: 4px 10px !important;
      }
      :root[data-dsh-thought-fold] [data-chat-flow-kind="turn-process"] > button,
      :root[data-dsh-thought-fold] button[data-turn-process] {
        box-sizing: border-box !important;
        display: inline-flex !important;
        align-items: center !important;
        justify-content: flex-start !important;
        width: fit-content !important;
        max-width: 100% !important;
        min-height: 28px !important;
        padding: 0 12px 0 10px !important;
        border: 1px solid color-mix(in srgb, var(--dsw-alias-border-l2, #d9dde3) 72%, transparent) !important;
        border-radius: 999px !important;
        background: color-mix(in srgb, var(--dsw-alias-label-primary, #1f2328) 4.5%, transparent) !important;
        color: var(--dsw-alias-label-secondary, #68707d) !important;
        box-shadow: 0 1px 2px rgba(15, 23, 42, .03) !important;
        font-size: 12px !important;
        font-weight: 500 !important;
        line-height: 26px !important;
        letter-spacing: -.01em !important;
        cursor: pointer !important;
        user-select: none !important;
        transition: background-color .16s ease, border-color .16s ease, color .16s ease, box-shadow .16s ease, transform .1s ease !important;
      }
      :root[data-dsh-thought-fold] [data-chat-flow-kind="turn-process"] > button::before,
      :root[data-dsh-thought-fold] button[data-turn-process]::before {
        content: "";
        display: inline-block;
        width: 12px;
        height: 12px;
        margin-right: 6px;
        flex: none;
        background-color: currentColor;
        opacity: .72;
        -webkit-mask: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='currentColor' stroke-width='1.6' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='M3 5l3.5 3L3 11M8 11h5'/%3E%3C/svg%3E") no-repeat center / contain;
        mask: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='currentColor' stroke-width='1.6' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='M3 5l3.5 3L3 11M8 11h5'/%3E%3C/svg%3E") no-repeat center / contain;
      }
      :root[data-dsh-thought-fold] [data-chat-flow-kind="turn-process"] > button:hover,
      :root[data-dsh-thought-fold] button[data-turn-process]:hover {
        border-color: color-mix(in srgb, var(--dsw-alias-brand-primary, #4f6ef7) 45%, transparent) !important;
        background: var(--dsw-alias-interactive-bg-hover, rgba(15, 23, 42, .06)) !important;
        color: var(--dsw-alias-label-primary, #1f2328) !important;
        box-shadow: 0 2px 5px rgba(15, 23, 42, .06) !important;
      }
      :root[data-dsh-thought-fold] [data-chat-flow-kind="turn-process"] > button[data-open],
      :root[data-dsh-thought-fold] button[data-turn-process][data-open] {
        border-color: color-mix(in srgb, var(--dsw-alias-brand-primary, #4f6ef7) 38%, transparent) !important;
        background: color-mix(in srgb, var(--dsw-alias-brand-primary, #4f6ef7) 9%, transparent) !important;
        color: var(--dsw-alias-brand-primary, #4f6ef7) !important;
      }
      :root[data-dsh-thought-fold] [data-chat-flow-kind="turn-process"] > button:focus-visible,
      :root[data-dsh-thought-fold] button[data-turn-process]:focus-visible {
        outline: 2px solid var(--dsw-alias-brand-primary, #4f6ef7) !important;
        outline-offset: 2px !important;
      }
      :root[data-dsh-thought-fold] [data-chat-flow-kind="turn-process"] > button:active,
      :root[data-dsh-thought-fold] button[data-turn-process]:active { transform: scale(.985) !important; }
      :root[data-dsh-thought-fold] [data-chat-flow-kind="turn-process"] svg,
      :root[data-dsh-thought-fold] button[data-turn-process] svg {
        width: 13px !important;
        height: 13px !important;
        margin-left: 5px !important;
        flex: none !important;
        color: inherit !important;
        opacity: .68 !important;
      }
      :root[data-dsh-thought-fold] [data-chat-flow-kind="turn-process"] [data-turn-process-tool-calls],
      :root[data-dsh-thought-fold] [data-chat-flow-kind="turn-process"] [data-turn-process-messages],
      :root[data-dsh-thought-fold] [data-chat-flow-kind="turn-process"] [data-turn-process-subagents] { font-variant-numeric: tabular-nums; }
      :root[data-dsh-thought-fold="minimal"] [data-chat-flow-kind="turn-process"] > button,
      :root[data-dsh-thought-fold="minimal"] button[data-turn-process] {
        padding-inline: 4px 7px !important;
        border-color: transparent !important;
        background: transparent !important;
        box-shadow: none !important;
      }
      :root[data-dsh-thought-fold="clean"] [data-chat-flow-kind="turn-process"] > button,
      :root[data-dsh-thought-fold="clean"] button[data-turn-process] {
        min-height: 32px !important;
        border-radius: 8px !important;
        background: var(--dsw-alias-bg-layer-2, #f7f8fa) !important;
      }

      [data-dsh-tf-native-suspended] { display: none !important; }
      [data-dsh-tf-native-reveal]:not([data-dsh-tf-hidden]) { display: block !important; content-visibility: visible !important; }
      [data-turn-process-inline][data-dsh-tf-native-reveal]:not([data-dsh-tf-hidden]) { margin-bottom: 0 !important; }
      [data-dsh-tf-hidden][hidden="until-found"] { content-visibility: hidden; height: 0 !important; min-height: 0 !important; margin-block: 0 !important; padding-block: 0 !important; border-block-width: 0 !important; overflow: clip; }
      .dsh-tf-fold-button {
        box-sizing: border-box;
        display: inline-flex;
        align-items: center;
        justify-content: flex-start;
        align-self: flex-start;
        width: fit-content;
        max-width: 100%;
        min-height: 32px;
        padding: 4px 12px;
        border: 1px solid var(--dsw-alias-border-l2, #d9dde3);
        border-radius: 999px;
        background: var(--dsw-alias-bg-layer-1, #fff);
        color: var(--dsw-alias-label-secondary, #68707d);
        font: inherit;
        font-size: 12px;
        line-height: 22px;
        cursor: pointer;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }
      .dsh-tf-fold-button::before { content: ''; width: 7px; height: 7px; margin: 4px 8px 0 0; border: solid currentColor; border-width: 1.5px 0 0 1.5px; transform: rotate(45deg); flex: none; }
      .dsh-tf-fold-button[aria-expanded="false"]::before { transform: rotate(225deg); margin-top: -3px; }
      .dsh-tf-fold-button[hidden] { display: none !important; }
      .dsh-tf-fold-button:hover { color: var(--dsw-alias-brand-primary, #4f6ef7); border-color: currentColor; }
      .dsh-tf-fold-button:focus-visible { outline: 2px solid var(--dsw-alias-brand-primary, #4f6ef7); outline-offset: 2px; }
      [data-dsh-tf-bottom] { margin-block: 8px 4px !important; }
      [data-dsh-tf-floating] { position: fixed; z-index: 8; height: 36px; box-shadow: 0 3px 14px rgba(15, 23, 42, .12); pointer-events: auto; }
      :root[data-dsh-thought-fold="minimal"] .dsh-tf-fold-button:not([data-dsh-tf-floating]) { border-color: transparent; background: transparent; }
      :root[data-dsh-thought-fold="clean"] .dsh-tf-fold-button { border-radius: 8px; background: var(--dsw-alias-bg-layer-2, #f7f8fa); }

      .dsh-tf-settings {
        --tf-bg: var(--dsw-alias-bg-layer-1, #fff);
        --tf-bg-soft: var(--dsw-alias-bg-layer-2, #f7f8fa);
        --tf-text: var(--dsw-alias-label-primary, #1f2328);
        --tf-muted: var(--dsw-alias-label-secondary, #68707d);
        --tf-subtle: var(--dsw-alias-label-tertiary, #8b93a1);
        --tf-border: var(--dsw-alias-border-l2, #e5e7eb);
        --tf-accent: var(--dsw-alias-brand-primary, #4f6ef7);
        --tf-success: var(--dsw-alias-state-success-primary, #16803d);
        --tf-success-bg: var(--dsw-alias-state-success-tertiary, rgba(22, 163, 74, .09));
        box-sizing: border-box;
        width: 100%;
        max-width: 720px;
        min-width: 0;
        margin: 0 auto;
        padding: 8px 4px 28px;
        color: var(--tf-text);
        font-family: Inter, "SF Pro Text", "PingFang SC", "Microsoft YaHei", system-ui, sans-serif;
      }
      .dsh-tf-settings *, .dsh-tf-settings *::before, .dsh-tf-settings *::after { box-sizing: border-box; }
      .dsh-tf-header {
        display: flex;
        flex-direction: column;
        gap: 8px;
        min-width: 0;
        margin-bottom: 24px;
        padding: 4px 2px 20px;
        border-bottom: 1px solid var(--tf-border);
      }
      .dsh-tf-title-row { display: flex; align-items: center; gap: 10px; min-width: 0; }
      .dsh-tf-title-icon { display: inline-flex; flex: none; color: var(--tf-accent); }
      .dsh-tf-title {
        min-width: 0;
        margin: 0;
        overflow: hidden;
        color: var(--tf-text);
        font-size: 18px;
        font-weight: 650;
        line-height: 1.35;
        letter-spacing: -.012em;
        text-overflow: ellipsis;
        white-space: nowrap;
      }
      .dsh-tf-status {
        flex: none;
        margin-left: auto;
        padding: 3px 9px;
        border: 1px solid color-mix(in srgb, var(--tf-success) 34%, transparent);
        border-radius: 999px;
        background: var(--tf-success-bg);
        color: var(--tf-success);
        font-size: 11px;
        font-weight: 600;
        line-height: 1.45;
        white-space: nowrap;
      }
      .dsh-tf-status[data-enabled="false"] {
        border-color: color-mix(in srgb, var(--tf-subtle) 28%, transparent);
        background: color-mix(in srgb, var(--tf-subtle) 8%, transparent);
        color: var(--tf-subtle);
      }
      .dsh-tf-subtitle { max-width: 620px; margin: 0; color: var(--tf-muted); font-size: 13px; line-height: 1.55; }
      .dsh-tf-feedback { display: flex; align-items: flex-start; gap: 7px; margin: -8px 2px 16px; font-size: 12px; line-height: 1.5; }
      .dsh-tf-feedback svg { flex: none; margin-top: 1px; }
      .dsh-tf-toast { color: var(--tf-success); }
      .dsh-tf-error { color: var(--dsw-alias-state-error-primary, #d54941); }
      .dsh-tf-card {
        margin: 0 0 16px;
        padding: 20px 22px;
        border: 1px solid var(--tf-border);
        border-radius: 12px;
        background: var(--tf-bg);
      }
      .dsh-tf-card-title {
        display: flex;
        align-items: center;
        gap: 8px;
        margin: 0 0 4px;
        color: var(--tf-text);
        font-size: 14px;
        font-weight: 650;
        line-height: 1.4;
      }
      .dsh-tf-card-title svg { color: var(--tf-muted); }
      .dsh-tf-row {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 24px;
        min-width: 0;
        padding: 16px 0;
        border-bottom: 1px solid color-mix(in srgb, var(--tf-border) 76%, transparent);
      }
      .dsh-tf-row:last-child { padding-bottom: 0; border-bottom: 0; }
      .dsh-tf-row-copy { min-width: 0; flex: 1; }
      .dsh-tf-label { color: var(--tf-text); font-size: 14px; font-weight: 600; line-height: 1.45; }
      .dsh-tf-desc { max-width: 500px; margin-top: 4px; color: var(--tf-muted); font-size: 13px; line-height: 1.55; overflow-wrap: anywhere; }
      .dsh-tf-control { display: flex; width: 160px; flex: 0 0 160px; justify-content: flex-end; }
      .dsh-tf-select {
        width: 160px;
        height: 36px;
        padding: 0 34px 0 12px;
        border: 1px solid var(--tf-border);
        border-radius: 8px;
        outline: none;
        background-color: var(--tf-bg);
        color: var(--tf-text);
        font: inherit;
        font-size: 13px;
        line-height: 34px;
        cursor: pointer;
      }
      .dsh-tf-select option { background-color: var(--tf-bg); color: var(--tf-text); }
      .dsh-tf-select:hover:not(:disabled) { border-color: color-mix(in srgb, var(--tf-accent) 44%, var(--tf-border)); }
      .dsh-tf-select:focus-visible { border-color: var(--tf-accent); outline: 2px solid color-mix(in srgb, var(--tf-accent) 26%, transparent); outline-offset: 2px; }
      .dsh-tf-select:disabled { cursor: not-allowed; opacity: .52; }
      .dsh-tf-toggle { position: relative; display: inline-flex; width: 44px; height: 24px; flex: 0 0 auto; }
      .dsh-tf-toggle input { position: absolute; width: 1px; height: 1px; margin: -1px; padding: 0; border: 0; clip: rect(0 0 0 0); overflow: hidden; }
      .dsh-tf-toggle span { position: absolute; inset: 0; border-radius: 999px; background: color-mix(in srgb, var(--tf-muted) 30%, transparent); cursor: pointer; transition: background-color .18s ease; }
      .dsh-tf-toggle span::before { content: ''; position: absolute; top: 3px; left: 3px; width: 18px; height: 18px; border-radius: 50%; background: #fff; box-shadow: 0 1px 2px rgba(15, 23, 42, .16); transition: transform .18s cubic-bezier(.2,.8,.2,1); }
      .dsh-tf-toggle input:checked + span { background: var(--tf-accent); }
      .dsh-tf-toggle input:checked + span::before { transform: translateX(20px); }
      .dsh-tf-toggle input:focus-visible + span { outline: 2px solid var(--tf-accent); outline-offset: 2px; }
      .dsh-tf-toggle input:disabled + span { cursor: not-allowed; opacity: .48; }
      .dsh-tf-assurance {
        display: flex;
        align-items: flex-start;
        gap: 8px;
        margin: 4px 2px 0;
        color: var(--tf-subtle);
        font-size: 12px;
        line-height: 1.55;
      }
      .dsh-tf-assurance svg { flex: none; margin-top: 1px; color: var(--tf-muted); }
      @media (max-width: 640px) {
        .dsh-tf-settings { padding-inline: 0; }
        .dsh-tf-card { padding: 18px; }
        .dsh-tf-row { align-items: flex-start; gap: 14px; }
        .dsh-tf-control { width: auto; flex-basis: auto; }
      }
      @media (max-width: 480px) {
        .dsh-tf-header { margin-bottom: 18px; }
        .dsh-tf-row { flex-direction: column; }
        .dsh-tf-control { width: 100%; justify-content: flex-start; }
        .dsh-tf-select { width: 100%; }
      }
      @media (prefers-reduced-motion: reduce) {
        :root[data-dsh-thought-fold] [data-chat-flow-kind="turn-process"] > button,
        :root[data-dsh-thought-fold] button[data-turn-process],
        .dsh-tf-toggle span,
        .dsh-tf-toggle span::before { transition: none !important; }
      }
    `;

    // Pure boundary planner. Inputs contain only owned scalar facts, never live host objects.
    const PROCESS_INDEPENDENT = new Set(['system-prompt', 'user', 'steering', 'turn-process', 'turn-error', 'turn-max-tokens', 'turn-tail']);
    function planSpecialProcess(items, { closed, endSeq, answerKey }) {
      const process = item => !PROCESS_INDEPENDENT.has(item.kind);
      let seenProcess = false;
      let hasInsertion = false;
      for (const item of items) {
        if ((item.kind === 'user' || item.kind === 'steering') && seenProcess) hasInsertion = true;
        if (process(item)) seenProcess = true;
      }
      const interrupted = items.some(item => item.interrupted || item.kind === 'turn-error' || item.kind === 'turn-max-tokens');
      if (!hasInsertion && !(closed && (interrupted || !answerKey))) return null;
      // Only a closed Turn has a final/partial answer to retain. Running tails stay visible.
      const closingText = closed ? items.findLast(item => item.kind === 'assistant-step' && item.hasText && item.settled) : null;
      const retained = new Set(closed ? [answerKey, closingText?.key].filter(Boolean) : []);
      const segments = [];
      let run = [];
      function finish(boundary) {
        if (!run.length) return;
        // A lone reasoning disclosure already owns its native top control.
        if (run.length === 1 && run[0].onlyReasoning) { run = []; return; }
        const validSeqs = run.every(item => Number.isFinite(item.seq));
        const end = boundary ? boundary.seq : endSeq;
        const ended = closed
          ? Number.isFinite(endSeq) && Number.isFinite(end) && validSeqs && run.every(item => item.seq < end && item.seq < endSeq && !item.running)
          : boundary && (boundary.kind === 'user' || boundary.kind === 'steering') && validSeqs && Number.isFinite(end) && run.every(item => item.seq < end && item.settled && item.stepClosed && Number.isFinite(item.stepEndSeq) && item.stepEndSeq <= end);
        if (ended) segments.push({
          boundary: boundary?.key ?? 'turn-end',
          keys: run.map(item => item.key),
          interrupted: closed && interrupted,
          label: closed && interrupted ? '已中断的思考与工具调用' : '思考与工具调用'
        });
        run = [];
      }
      for (const item of items) {
        if (item.kind === 'turn-process') continue;
        if (!process(item) || retained.has(item.key)) finish(item);
        else run.push(item);
      }
      finish(null);
      return { segments, hasInsertion, interrupted };
    }

    // Conversation-scoped enhancement. Never wrap/move React-owned message rows.
    const FLOW = '[data-chat-flow]';
    const OWNED = 'data-dsh-tf-owned';
    const HIDDEN = 'data-dsh-tf-hidden';
    const INDEPENDENT = new Set(['system-prompt', 'user', 'steering', 'turn-process', 'turn-error', 'turn-max-tokens', 'turn-tail']);
    const runtimeListeners = new Set();
    const runtimeControllers = new Set();
    const scopeControllers = new WeakMap();
    let runtimeConfig = null;
    let floatingOwner = null;

    function makeFoldController(scope, marker, getNode, win = window) {
      if (typeof win.MutationObserver !== 'function' || typeof win.requestAnimationFrame !== 'function') return { dispose() {}, refresh() {} };
      scopeControllers.get(scope)?.dispose();
      const doc = scope.ownerDocument;
      let disposed = false;
      let frame = 0;
      let dirty = true;
      let groups = new Map();
      let flows = [];
      let target = null;
      let anchor = null;
      const choices = new Map();
      const hiddenRows = new Set();
      const previousHidden = new Map();
      const resizeTargets = new Set();
      const nativeLeases = new Map();
      const nativeReveals = new Set();
      let requestedNative = new Set();
      let requestedReveals = new Set();
      const proxy = makeButton('收起本段过程');
      proxy.dataset.dshTfFloating = '';
      proxy.hidden = true;
      marker.appendChild(proxy);

      function makeButton(label) {
        const button = doc.createElement('button');
        button.type = 'button';
        button.className = 'dsh-tf-fold-button';
        button.setAttribute(OWNED, '');
        button.textContent = label;
        return button;
      }
      function setText(element, value) {
        if (element.textContent !== value) element.textContent = value;
      }
      function setHidden(row, value) {
        if (value) {
          if (!hiddenRows.has(row)) previousHidden.set(row, { value: row.getAttribute('hidden'), nativeOwned: row.hasAttribute('data-turn-process-hidden') });
          if (!row.hasAttribute(HIDDEN)) row.setAttribute(HIDDEN, '');
          if (row.getAttribute('hidden') !== 'until-found') row.setAttribute('hidden', 'until-found');
          hiddenRows.add(row);
        } else {
          if (row.hasAttribute(HIDDEN)) row.removeAttribute(HIDDEN);
          // Native compact mode may have taken ownership since we hid this row.
          if (previousHidden.has(row) && !row.hasAttribute('data-turn-process-hidden') && row.getAttribute('hidden') === 'until-found') {
            const original = previousHidden.get(row);
            if (original.value === null || original.nativeOwned) row.removeAttribute('hidden');
            else row.setAttribute('hidden', original.value);
          }
          previousHidden.delete(row);
          hiddenRows.delete(row);
        }
      }
      function open(group) {
        return group.kind === 'native' ? group.top.getAttribute('aria-expanded') === 'true' : choices.get(group.id) === true;
      }
      function visible(element) {
        if (!element?.isConnected || element.getClientRects().length === 0) return false;
        if (element.closest('[' + HIDDEN + ']')) return false;
        const blocked = element.closest('[hidden]:not([hidden="until-found"]), [data-turn-process-hidden]');
        return !blocked || blocked.hasAttribute('data-dsh-tf-native-reveal');
      }
      function hideProxy() {
        proxy.hidden = true;
        target = null;
        if (floatingOwner === controller) floatingOwner = null;
      }
      function schedule(structural = false) {
        if (disposed) return;
        dirty = dirty || structural;
        if (!frame) frame = win.requestAnimationFrame(flush);
      }
      function forget(group) {
        group.bottom.remove();
        if (group.kind === 'compat') group.top.remove();
      }
      function focusTop(group) {
        const top = group.top;
        if (!top.isConnected) return;
        top.focus({ preventScroll: true });
        anchor = { top, offset: Math.max(8, top.getBoundingClientRect().top - scope.getBoundingClientRect().top) };
        // An off-screen header should land near the top, not at its old negative offset.
        anchor.offset = Math.min(anchor.offset, Math.max(8, scope.clientHeight / 3));
      }
      function collapse(group) {
        // Reject a proxy captured just before a React replacement/session transition.
        if (disposed || !scope.isConnected || !groups.has(group.id) || groups.get(group.id) !== group || !open(group)) return;
        if (!group.top.isConnected || !group.members.some(row => row.isConnected)) return;
        if (group.members.some((row, index) => row.getAttribute('data-chat-flow-key') !== group.memberKeys[index] || row.getAttribute('data-chat-turn') !== group.turn)) return;
        if (group.kind === 'native' && group.top.getAttribute('data-turn-process') !== group.turn) return;
        focusTop(group);
        if (group.kind === 'native') group.top.click();
        else choices.set(group.id, false);
        hideProxy();
        schedule(true);
      }
      proxy.addEventListener('click', () => { if (target) collapse(target); });

      function clickNativeQuietly(button) {
        const focused = doc.activeElement;
        const scrollTop = scope.scrollTop;
        const scrollLeft = scope.scrollLeft;
        button.click();
        if (focused?.isConnected && typeof focused.focus === 'function') focused.focus({ preventScroll: true });
        if (doc.activeElement === button && focused !== button) button.blur();
        scope.scrollTop = scrollTop;
        scope.scrollLeft = scrollLeft;
      }
      function releaseNative(button, lease) {
        const replaced = [...nativeLeases].some(([other, current]) => other !== button && current.row === lease.row && requestedNative.has(other));
        if (!replaced) lease.row?.removeAttribute('data-dsh-tf-native-suspended');
        nativeLeases.delete(button);
      }
      function suspendNative(button, members) {
        requestedNative.add(button);
        let lease = nativeLeases.get(button);
        if (!lease) {
          lease = { row: button.closest('[data-chat-flow-key]') };
          nativeLeases.set(button, lease);
        }
        // Pure presentation takeover: never click or mutate the native disclosure state.
        // This remains reversible even if React replaces the native button or commits late.
        for (const row of members) {
          requestedReveals.add(row);
          nativeReveals.add(row);
          if (!row.hasAttribute('data-dsh-tf-native-reveal')) row.setAttribute('data-dsh-tf-native-reveal', '');
        }
        lease.row?.setAttribute('data-dsh-tf-native-suspended', '');
        return true;
      }
      function groupLabel(group) {
        return `第 ${group.turn} 轮${group.segment ? `第 ${group.segment} 段` : ''}思考与工具调用`;
      }
      function descriptors(flow) {
        // One bounded read of the current conversation's direct flow rows per structural batch.
        const rows = Array.from(flow.children).filter(row => row.hasAttribute('data-chat-flow-key'));
        const byTurn = new Map();
        const meta = new Map();
        for (const row of rows) {
          const key = row.getAttribute('data-chat-flow-key');
          const node = getNode(key);
          const turn = row.getAttribute('data-chat-turn');
          meta.set(row, node);
          if (turn !== null && turn !== '') {
            if (!byTurn.has(turn)) byTurn.set(turn, []);
            byTurn.get(turn).push(row);
          }
        }
        const results = [];
        for (const [turn, turnRows] of byTurn) {
          const control = turnRows.find(row => row.getAttribute('data-chat-flow-kind') === 'turn-process');
          const top = control?.querySelector('button[data-turn-process]');
          const controlNode = control && meta.get(control);
          const spec = controlNode?.data;
          const id = `${turn}:${spec?.answerStep ?? 'native'}`;
          const items = turnRows.map(row => {
            const node = meta.get(row);
            const location = node?.location;
            const status = node?.data?.status;
            const root = node?.kind === 'tool-call' ? node.data?.root : null;
            const hasText = node?.kind === 'assistant-step' && node.data?.blocks?.some(block => block.kind === 'text' && typeof block.text === 'string' && block.text.trim() !== '');
            return {
              key: row.getAttribute('data-chat-flow-key'), kind: node?.kind ?? 'unknown', seq: node?.anchorSeq,
              hasText: !!hasText,
              onlyReasoning: node?.kind === 'assistant-step' && node.data?.blocks?.some(block => block.kind === 'reasoning') && node.data.blocks.every(block => block.kind === 'reasoning' || (block.kind === 'text' && typeof block.text === 'string' && block.text.trim() === '')),
              running: status === 'running' || (node?.kind === 'tool-call' && root != null && root.kind == null),
              settled: status === 'settled' || status === 'interrupted' || (node?.kind === 'tool-call' && root?.kind != null),
              interrupted: status === 'interrupted' || root?.error?.code === 'interrupted',
              stepClosed: location?.kind === 'step' && location.step?.status === 'closed',
              stepEndSeq: location?.kind === 'step' ? location.step?.end?.seq : undefined
            };
          });
          const turnLocation = controlNode?.location?.turn ?? turnRows.map(row => meta.get(row)?.location?.turn).find(Boolean);
          const answerRow = turnRows.find(row => {
            const node = meta.get(row);
            return node?.kind === 'assistant-step' && spec?.answerStep != null && node.data?.step === spec.answerStep;
          });
          const tail = items.find(item => item.kind === 'turn-tail');
          const special = planSpecialProcess(items, {
            closed: turnLocation?.status === 'closed',
            endSeq: turnLocation?.end?.seq ?? tail?.seq,
            answerKey: answerRow?.getAttribute('data-chat-flow-key')
          });
          if (special) {
            const nativeMembers = turnRows.filter(row => row.hasAttribute('data-turn-process-member'));
            const inlineReasoning = turnRows.filter(row => meta.get(row)?.kind === 'assistant-step').flatMap(row => Array.from(row.querySelectorAll('[data-turn-process-inline]')));
            const whole = groups.get(id);
            if (whole && !whole.segment) for (const segment of special.segments) {
              const segmentId = `${turn}:segment:${segment.boundary}`;
              if (!choices.has(segmentId)) choices.set(segmentId, open(whole));
            }
            if (top && !suspendNative(top, [...nativeMembers, ...inlineReasoning])) continue;
            special.segments.forEach((segment, index) => {
              const keys = new Set(segment.keys);
              const members = turnRows.filter(row => keys.has(row.getAttribute('data-chat-flow-key')));
              if (members.length) results.push({ id: `${turn}:segment:${segment.boundary}`, kind: 'compat', members, flow, turn, segment: index + 1, label: segment.label });
            });
            continue;
          }
          if (top) {
            const members = turnRows.filter(row => row.hasAttribute('data-turn-process-member'));
            if (members.length) results.push({ id, kind: 'native', top, members, flow, turn });
            continue;
          }
          // Fail open unless the host has positively identified a closed Turn and answer.
          // This works in normal mode and while older pages disable native compact controls.
          const location = controlNode?.location;
          if (!spec || location?.turn?.status !== 'closed' || !Number.isFinite(spec.answerAnchorSeq) || !Number.isFinite(spec.processStartSeq) || spec.answerStep == null) continue;
          const answer = turnRows.find(row => {
            const node = meta.get(row);
            return node?.kind === 'assistant-step' && node.data?.step === spec.answerStep;
          });
          if (!answer || meta.get(answer)?.data?.status === 'running') continue;
          const members = turnRows.filter(row => {
            const node = meta.get(row);
            return node && !INDEPENDENT.has(node.kind) && row !== answer && node.anchorSeq >= spec.processStartSeq && node.anchorSeq < spec.answerAnchorSeq;
          });
          if (members.length) results.push({ id, kind: 'compat', members, flow, turn });
        }
        return results;
      }
      function reconcile() {
        requestedNative = new Set();
        requestedReveals = new Set();
        flows = Array.from(scope.querySelectorAll(FLOW));
        const next = new Map();
        const wantedHidden = new Set();
        // A conversation displays one chat flow. Ignore nested preview transcripts.
        const flow = flows.find(node => node.closest('[data-conversation-scroll]') === scope);
        if (flow) for (const desc of descriptors(flow)) {
          let group = groups.get(desc.id);
          let created = false;
          if (group && (group.kind !== desc.kind || group.flow !== desc.flow || (group.kind === 'native' && group.top !== desc.top))) {
            // Preserve a user choice across a native/compatibility handover.
            choices.set(group.id, open(group));
            forget(group);
            group = null;
          }
          if (!group) {
            created = true;
            group = { ...desc, bottom: makeButton('收起本段过程') };
            if (desc.kind === 'compat') {
              group.top = makeButton('展开思考与工具调用');
              group.top.dataset.dshTfCompat = '';
              group.top.addEventListener('click', () => {
                if (!groups.has(group.id) || groups.get(group.id) !== group) return;
                if (open(group)) collapse(group);
                else { choices.set(group.id, true); schedule(true); }
              });
            }
            group.bottom.dataset.dshTfBottom = '';
            group.bottom.addEventListener('click', () => collapse(group));
          }
          Object.assign(group, desc);
          group.memberKeys = group.members.map(row => row.getAttribute('data-chat-flow-key'));
          next.set(group.id, group);
          if (group.kind === 'native' && created) {
            const desired = choices.get(group.id) === true;
            if (open(group) !== desired) {
              group.pendingOpen = { desired, attempts: 0 };
              clickNativeQuietly(group.top);
              schedule(true);
            }
          }
          if (group.kind === 'compat') {
            const first = group.members[0];
            if (group.top.nextSibling !== first) flow.insertBefore(group.top, first);
            const expanded = open(group);
            group.top.setAttribute('aria-expanded', String(expanded));
            group.top.setAttribute('aria-label', `${expanded ? '收起' : '展开'}${groupLabel(group)}`);
            setText(group.top, `${expanded ? '收起' : '展开'}${group.label || '思考与工具调用'}${group.segment ? ` · 第 ${group.segment} 段` : ''} · ${group.members.length} 项`);
            for (const row of group.members) if (!expanded) wantedHidden.add(row);
          } else {
            if (group.pendingOpen && open(group) !== group.pendingOpen.desired && group.pendingOpen.attempts++ < 2) {
              schedule(true);
            } else {
              delete group.pendingOpen;
              choices.set(group.id, open(group));
            }
          }
          const last = group.members[group.members.length - 1];
          if (last.nextSibling !== group.bottom) flow.insertBefore(group.bottom, last.nextSibling);
          group.bottom.hidden = !open(group);
          group.bottom.setAttribute('aria-label', `收起${groupLabel(group)}`);
        }
        for (const [id, group] of groups) if (!next.has(id)) forget(group);
        groups = next;
        for (const row of hiddenRows) if (!wantedHidden.has(row)) setHidden(row, false);
        for (const row of wantedHidden) setHidden(row, true);
        for (const [button, lease] of nativeLeases) if (!requestedNative.has(button)) releaseNative(button, lease);
        for (const row of nativeReveals) if (!requestedReveals.has(row)) {
          row.removeAttribute('data-dsh-tf-native-reveal');
          nativeReveals.delete(row);
        }
        if (resizeObserver) {
          const wanted = new Set([scope, scope.querySelector('[data-composer-seat]'), ...flows].filter(Boolean));
          for (const node of resizeTargets) if (!wanted.has(node)) { resizeObserver.unobserve(node); resizeTargets.delete(node); }
          for (const node of wanted) if (!resizeTargets.has(node)) { resizeObserver.observe(node); resizeTargets.add(node); }
        }
      }
      function layout() {
        hideProxy();
        if (!visible(scope)) return;
        const bounds = scope.getBoundingClientRect();
        const viewport = win.visualViewport;
        const viewportTop = viewport?.offsetTop ?? 0;
        const viewportBottom = viewportTop + (viewport?.height ?? win.innerHeight);
        const topEdge = Math.max(bounds.top, viewportTop) + 8;
        const composer = scope.querySelector('[data-composer-seat]');
        const composerRect = visible(composer) ? composer.getBoundingClientRect() : null;
        const bottomEdge = Math.min(bounds.bottom, viewportBottom, composerRect && composerRect.bottom > topEdge ? composerRect.top : Infinity) - 8;
        if (bottomEdge - topEdge < 44) return;
        let chosen = null;
        let chosenTop = -Infinity;
        for (const group of groups.values()) {
          if (!open(group) || !group.top.isConnected) continue;
          const members = group.members.filter(visible);
          if (!members.length) continue;
          const start = Math.min(group.top.getBoundingClientRect().top, members[0].getBoundingClientRect().top);
          const end = group.bottom.getBoundingClientRect();
          const lastBottom = members[members.length - 1].getBoundingClientRect().bottom;
          if (start >= bottomEdge - 36 || lastBottom <= topEdge) continue;
          // Visible inline button owns its place; only obscured bottoms need a proxy.
          if (end.height > 0 && end.top >= topEdge && end.bottom <= bottomEdge) continue;
          if (lastBottom < bottomEdge - 36) continue;
          if (start >= chosenTop) { chosen = group; chosenTop = start; }
        }
        if (!chosen) return;
        const column = chosen.flow.getBoundingClientRect();
        const left = Math.max(column.left, bounds.left + 8, viewport?.offsetLeft ?? 0);
        const right = Math.min(column.right, bounds.right - 8, (viewport?.offsetLeft ?? 0) + (viewport?.width ?? win.innerWidth));
        if (right - left < 100) return;
        floatingOwner?.hideProxy();
        floatingOwner = controller;
        target = chosen;
        proxy.hidden = false;
        proxy.style.left = `${left}px`;
        proxy.style.top = `${bottomEdge - 36}px`;
        proxy.style.maxWidth = `${right - left}px`;
        proxy.setAttribute('aria-label', `收起${groupLabel(chosen)}`);
        proxy.title = `仅收起${groupLabel(chosen)}，不影响其他已展开内容`;
      }
      function flush() {
        frame = 0;
        if (disposed) return;
        try {
          if (dirty) { dirty = false; reconcile(); }
          if (anchor) {
            const { top, offset } = anchor;
            anchor = null;
            if (top.isConnected) scope.scrollTop += top.getBoundingClientRect().top - scope.getBoundingClientRect().top - offset;
          }
          layout();
        } catch (error) {
          // Enhancement failures must never leave content hidden or take down Chat.
          dispose();
          console.warn('[dsh-thought-fold] 当前会话增强已安全停用', error);
        }
      }
      const onScroll = () => schedule();
      const onChange = () => schedule(true);
      const onFound = event => {
        for (const group of groups.values()) if (group.kind === 'compat' && group.members.some(row => row === event.target || row.contains(event.target))) {
          choices.set(group.id, true);
          for (const row of group.members) setHidden(row, false);
          schedule(true);
        }
      };
      const observer = new win.MutationObserver(records => {
        // Ignore owned controls and CSS/geometry writes, avoiding observer feedback loops.
        const external = records.some(record => {
          const element = record.target.nodeType === 1 ? record.target : record.target.parentElement;
          if (element?.closest('[' + OWNED + ']')) return false;
          if (record.type === 'childList') return [...record.addedNodes, ...record.removedNodes].some(node => node.nodeType !== 1 || !node.hasAttribute(OWNED));
          return true;
        });
        if (external) schedule(true);
      });
      const resizeObserver = typeof win.ResizeObserver === 'function' ? new win.ResizeObserver(() => schedule()) : null;
      const controller = { dispose, hideProxy, refresh: onChange };
      function dispose() {
        if (disposed) return;
        disposed = true;
        observer.disconnect();
        resizeObserver?.disconnect();
        if (frame) win.cancelAnimationFrame(frame);
        frame = 0;
        scope.removeEventListener('scroll', onScroll, true);
        scope.removeEventListener('beforematch', onFound, true);
        win.removeEventListener('resize', onScroll);
        win.visualViewport?.removeEventListener('resize', onScroll);
        win.visualViewport?.removeEventListener('scroll', onScroll);
        for (const row of hiddenRows) setHidden(row, false);
        for (const [button, lease] of nativeLeases) releaseNative(button, lease);
        for (const row of nativeReveals) row.removeAttribute('data-dsh-tf-native-reveal');
        nativeReveals.clear();
        for (const group of groups.values()) forget(group);
        groups.clear();
        hideProxy();
        proxy.remove();
        if (scopeControllers.get(scope) === controller) scopeControllers.delete(scope);
        runtimeControllers.delete(controller);
      }
      observer.observe(scope, { subtree: true, childList: true, attributes: true, attributeFilter: ['aria-expanded', 'data-open', 'data-turn-process-member', 'data-turn-process-hidden', 'data-chat-turn', 'data-chat-flow-key', 'data-chat-flow-kind', 'hidden', 'data-streaming'] });
      scope.addEventListener('scroll', onScroll, { passive: true, capture: true });
      scope.addEventListener('beforematch', onFound, true);
      win.addEventListener('resize', onScroll, { passive: true });
      win.visualViewport?.addEventListener('resize', onScroll, { passive: true });
      win.visualViewport?.addEventListener('scroll', onScroll, { passive: true });
      scopeControllers.set(scope, controller);
      runtimeControllers.add(controller);
      schedule(true);
      return controller;
    }

    function FoldDock(props) {
      // Missing optional host hook must not crash the composer on older deployments.
      return typeof props.useChat === 'function' ? h(FoldDockSession, props) : null;
    }

    function FoldDockSession({ useChat, foldSessionId }) {
      const marker = React.useRef(null);
      const store = React.useRef(null);
      const activeController = React.useRef(null);
      // The host's session hook is a live store, not copied transcript data.
      const nodes = useChat((snapshot) => snapshot.nodes);
      const timeline = useChat((snapshot) => snapshot.timeline);
      store.current = nodes;
      useEffect(() => { activeController.current?.refresh(); }, [nodes, timeline]);
      useEffect(() => {
        let controller = null;
        const update = () => {
          const scope = marker.current?.closest('[data-conversation-scroll]');
          if (!runtimeConfig?.enabled || !scope) { controller?.dispose(); controller = null; activeController.current = null; return; }
          try {
            if (!controller) controller = makeFoldController(scope, marker.current, key => store.current?.get(key));
            else controller.refresh();
            activeController.current = controller;
          } catch (error) {
            controller?.dispose();
            controller = null;
            activeController.current = null;
            console.warn('[dsh-thought-fold] 当前宿主不支持会话增强', error);
          }
        };
        runtimeListeners.add(update);
        update();
        return () => { runtimeListeners.delete(update); controller?.dispose(); activeController.current = null; };
      }, [foldSessionId]);
      return h('span', { ref: marker, 'data-dsh-tf-owned': '', style: { display: 'contents' } });
    }

    function mountStyles() {
      if (typeof document === 'undefined') return null;
      let style = document.getElementById(STYLE_ID);
      if (!style) {
        style = document.createElement('style');
        style.id = STYLE_ID;
        document.head.appendChild(style);
      }
      style.textContent = CSS;
      return style;
    }

    let runtimeOwner = null;
    let disposeRuntimeOwner = null;

    function clearRuntime() {
      runtimeConfig = null;
      // Let mounted docks release their local controller references as well.
      for (const listener of runtimeListeners) listener();
      for (const controller of runtimeControllers) controller.dispose();
      if (typeof document !== 'undefined' && document.documentElement) {
        document.documentElement.removeAttribute(ROOT_ATTRIBUTE);
      }
    }

    function syncRuntimeAppearance(config, owner) {
      if (!owner || runtimeOwner !== owner) return;
      runtimeConfig = config;
      for (const listener of runtimeListeners) listener();
      if (typeof document === 'undefined' || !document.documentElement) return;
      if (config.enabled && config.showLiveHud) {
        const style = ['codex', 'minimal', 'clean'].includes(config.foldStyle) ? config.foldStyle : 'codex';
        document.documentElement.setAttribute(ROOT_ATTRIBUTE, style);
      } else {
        document.documentElement.removeAttribute(ROOT_ATTRIBUTE);
      }
    }

    async function requestSettings(method = 'GET', body, signal) {
      const response = await fetch('/api/dsh-thought-fold', {
        signal,
        method,
        credentials: 'same-origin',
        headers: body ? { 'content-type': 'application/json' } : undefined,
        body: body ? JSON.stringify(body) : undefined
      });
      const payload = await response.json();
      if (!response.ok || payload.error) throw new Error(payload.error || `HTTP ${response.status}`);
      return payload;
    }

    function Toggle({ checked, onChange, disabled, label }) {
      return h('label', { className: 'dsh-tf-toggle' },
        h('input', {
          type: 'checkbox',
          checked,
          disabled,
          'aria-label': label,
          onChange: (event) => onChange(event.target.checked)
        }),
        h('span', { 'aria-hidden': true })
      );
    }

    function SettingRow({ label, description, children }) {
      return h('div', { className: 'dsh-tf-row' },
        h('div', { className: 'dsh-tf-row-copy' },
          h('div', { className: 'dsh-tf-label' }, label),
          h('div', { className: 'dsh-tf-desc' }, description)
        ),
        h('div', { className: 'dsh-tf-control' }, children)
      );
    }

    function ThoughtFoldSettingsView({ owner }) {
      const [config, setConfig] = useState(DEFAULT_CONFIG);
      const [busy, setBusy] = useState(true);
      const [writable, setWritable] = useState(true);
      const [toast, setToast] = useState('');
      const [error, setError] = useState('');
      const lifecycle = React.useRef(null);

      const refresh = useCallback(async (saveError = '') => {
        const life = lifecycle.current;
        if (!life || runtimeOwner !== owner) return;
        const version = ++owner.settingsVersion;
        const current = () => lifecycle.current === life && runtimeOwner === owner && owner.settingsVersion === version;
        setBusy(true);
        try {
          const payload = await requestSettings('GET', undefined, life.abort.signal);
          if (!current()) return;
          const nextConfig = { ...DEFAULT_CONFIG, ...(payload.config || {}) };
          setConfig(nextConfig);
          setWritable(payload.writable !== false);
          syncRuntimeAppearance(nextConfig, owner);
          setError(saveError || (payload.writable === false ? '设置服务不可用，当前配置为只读状态。' : ''));
        } catch (err) {
          if (!current()) return;
          clearRuntime();
          setWritable(false);
          setError(`${saveError ? saveError + '；' : ''}读取设置失败：${err.message}`);
        } finally {
          if (current()) setBusy(false);
        }
      }, [owner]);

      useEffect(() => {
        if (runtimeOwner !== owner) return;
        const life = { abort: new AbortController(), toastTimer: null };
        lifecycle.current = life;
        const cleanup = () => {
          life.abort.abort();
          if (life.toastTimer !== null) window.clearTimeout(life.toastTimer);
          if (lifecycle.current === life) lifecycle.current = null;
          owner.cleanups.delete(cleanup);
        };
        owner.cleanups.add(cleanup);
        refresh();
        return cleanup;
      }, [owner, refresh]);

      const update = useCallback(async (patch) => {
        const life = lifecycle.current;
        if (!life || runtimeOwner !== owner) return;
        const version = ++owner.settingsVersion;
        const current = () => lifecycle.current === life && runtimeOwner === owner && owner.settingsVersion === version;
        if (life.toastTimer !== null) window.clearTimeout(life.toastTimer);
        life.toastTimer = null;
        setToast('');
        setBusy(true);
        setConfig((currentConfig) => ({ ...currentConfig, ...patch }));
        try {
          const payload = await requestSettings('POST', { action: 'saveSettings', patch }, life.abort.signal);
          if (!current()) return;
          const nextConfig = { ...DEFAULT_CONFIG, ...(payload.config || {}) };
          setConfig(nextConfig);
          setWritable(payload.writable !== false);
          syncRuntimeAppearance(nextConfig, owner);
          setToast('设置已保存并立即生效。');
          setError('');
          life.toastTimer = window.setTimeout(() => {
            life.toastTimer = null;
            if (current()) setToast('');
          }, 2400);
        } catch (err) {
          if (!current()) return;
          await refresh(`保存失败：${err.message}`);
        } finally {
          if (current()) setBusy(false);
        }
      }, [owner, refresh]);

      const dependentDisabled = busy || !writable || !config.enabled;

      return h('div', { className: 'dsh-tf-settings' },
        h('header', { className: 'dsh-tf-header' },
          h('div', { className: 'dsh-tf-title-row' },
            h('span', { className: 'dsh-tf-title-icon' }, h(Icon, { name: 'brain', size: 21 })),
            h('h1', { className: 'dsh-tf-title' }, '思考与折叠'),
            h('span', { className: 'dsh-tf-status', 'data-enabled': String(Boolean(config.enabled)) }, config.enabled ? '已启用' : '已停用')
          ),
          h('p', { className: 'dsh-tf-subtitle' }, '增强原生过程折叠，提供兼容折叠及底部、浮动收起按钮；不改变 AI 的指令与输出方式。')
        ),
        toast && h('div', { className: 'dsh-tf-feedback dsh-tf-toast', role: 'status' }, h(Icon, { name: 'check', size: 14 }), h('span', null, toast)),
        error && h('div', { className: 'dsh-tf-feedback dsh-tf-error', role: 'alert' }, h(Icon, { name: 'info', size: 14 }), h('span', null, error)),
        h('section', { className: 'dsh-tf-card', 'aria-labelledby': 'dsh-tf-runtime-title' },
          h('h2', { className: 'dsh-tf-card-title', id: 'dsh-tf-runtime-title' }, h(Icon, { name: 'sliders' }), '运行'),
          h(SettingRow, { label: '启用插件', description: '启用过程折叠增强，以及每段过程的底部收起和按可见位置显示的浮动收起按钮。' },
            h(Toggle, { label: '启用插件', checked: Boolean(config.enabled), disabled: busy || !writable, onChange: (value) => update({ enabled: value }) })
          ),
          h('div', { className: 'dsh-tf-assurance' },
            h(Icon, { name: 'info', size: 15 }),
            h('span', null, '普通轮次复用原生折叠；插话按段收起，中断保留最后的已输出回答与提示；仍在运行的当前段保持可见。')
          )
        ),
        h('section', { className: 'dsh-tf-card', 'aria-labelledby': 'dsh-tf-appearance-title' },
          h('h2', { className: 'dsh-tf-card-title', id: 'dsh-tf-appearance-title' }, h(Icon, { name: 'palette' }), '外观'),
          h(SettingRow, { label: '增强运行状态样式', description: '调整原生过程控件与新增折叠按钮的外观；关闭此项不影响底部、浮动及兼容折叠功能。' },
            h(Toggle, { label: '增强运行状态样式', checked: Boolean(config.showLiveHud), disabled: dependentDisabled, onChange: (value) => update({ showLiveHud: value }) })
          ),
          h(SettingRow, { label: '折叠按钮样式', description: '选择过程控件的显示密度与边框形式。' },
            h('select', {
              className: 'dsh-tf-select',
              value: config.foldStyle,
              disabled: dependentDisabled || !config.showLiveHud,
              'aria-label': '折叠按钮样式',
              onChange: (event) => update({ foldStyle: event.target.value })
            },
            h('option', { value: 'codex' }, '经典'),
            h('option', { value: 'minimal' }, '极简'),
            h('option', { value: 'clean' }, '清晰'))
          )
        ),
        h('div', { className: 'dsh-tf-assurance' },
          h(Icon, { name: 'shield', size: 15 }),
          h('span', null, '无指令注入 · 不搬移消息行 · 原生与兼容过程折叠')
        )
      );
    }

    return {
      inject: ['slots'],
      apply(ctx) {
        disposeRuntimeOwner?.();
        clearRuntime();
        const owner = { cleanups: new Set(), settingsVersion: 0 };
        const style = mountStyles();
        const abort = new AbortController();
        let active = true;
        runtimeOwner = owner;
        if (style) style.__dshThoughtFoldOwner = owner;

        const version = ++owner.settingsVersion;
        requestSettings('GET', undefined, abort.signal)
          .then((payload) => {
            if (active && runtimeOwner === owner && owner.settingsVersion === version) {
              syncRuntimeAppearance({ ...DEFAULT_CONFIG, ...(payload.config || {}) }, owner);
            }
          })
          .catch(() => {
            if (active && runtimeOwner === owner && owner.settingsVersion === version) clearRuntime();
          });

        ctx.slots.inject('conversation.composer.dock', () => ctx.slots.register({
          name: 'conversation.composer.dock',
          id: 'thought-fold-controls',
          order: 100,
          inject: (sessionId) => ({ foldSessionId: sessionId })
        }, FoldDock));

        ctx.slots.inject('settings.section', () => ctx.slots.register({
          name: 'settings.section',
          id: 'thought-fold',
          order: 15,
          label: () => '思考折叠'
        }, () => h(ThoughtFoldSettingsView, { owner })));

        const dispose = () => {
          if (!active) return;
          active = false;
          abort.abort();
          for (const cleanup of owner.cleanups) cleanup();
          if (runtimeOwner === owner) {
            runtimeOwner = null;
            clearRuntime();
          }
          if (disposeRuntimeOwner === dispose) disposeRuntimeOwner = null;
          if (style?.__dshThoughtFoldOwner === owner) {
            style.remove?.();
          }
        };
        disposeRuntimeOwner = dispose;
        if (typeof ctx.effect === 'function') {
          ctx.effect(() => dispose, 'dsh-thought-fold:client-lifecycle');
        }
        return dispose;
      }
    };
  }
});
