import fs from 'node:fs';

const entry = fs.readFileSync(new URL('../src/client-entry.js', import.meta.url), 'utf8');
const planner = fs.readFileSync(new URL('../src/process-plan.js', import.meta.url), 'utf8');
const runtime = planner + '\n' + fs.readFileSync(new URL('../src/fold-runtime.js', import.meta.url), 'utf8');
const marker = '    // @fold-runtime';
if (entry.split(marker).length !== 2) throw new Error('Expected one fold-runtime insertion marker');
const built = '// Generated by scripts/build-client.js; edit src/client-entry.js, src/process-plan.js and src/fold-runtime.js.\n' + entry.replace(marker, runtime.trimEnd());
const target = new URL('../client.js', import.meta.url);
if (process.argv.includes('--check')) {
  if (fs.readFileSync(target, 'utf8') !== built) throw new Error('client.js is stale; run npm run build');
} else {
  fs.writeFileSync(target, built);
}
